DevOpsMetrics/DevOpsMetrics.Service/DataAccess/TableStorage/TableStorageCommonDA.cs, DevOpsMetrics/DevOpsMetrics.Web/Controllers/HomeController.cs
=> Final integration testing for table caching

DevOpsMetrics/DevOpsMetrics.NightlyProcessor.Function/AzureAlertProcessor.cs, DevOpsMetrics/DevOpsMetrics.NightlyProcessor.Function/NightlyProcessor.cs, DevOpsMetrics/DevOpsMetrics.NightlyProcessor.Function/ServiceApiClient.cs, DevOpsMetrics/DevOpsMetrics.Service/Common.cs, DevOpsMetrics/DevOpsMetrics.Service/Controllers/TableStorageController.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/TableStorage/AzureTableStorageDA.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/MonitoringEvent.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/TableStorageAuth.cs, DevOpsMetrics/DevOpsMetrics.Service/appsettings.json, DevOpsMetrics/DevOpsMetrics.Tests/Common.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/AzureMonitorTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/AzureTableStorageDATests.cs, DevOpsMetrics/DevOpsMetrics.Tests/appsettings.json, DevOpsMetrics/DevOpsMetrics.sln
=> Added monitoring shell

DevOpsMetrics/DevOpsMetrics.NightlyProcessor.Function/DevOpsMetrics.NightlyProcessor.Function.csproj, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/APIAccess/AzureDevOpsAPIAccess.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/TableStorage/AzureTableStorageDA.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/AzureDevOps/AzureDevOpsSettings.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/GitHub/GitHubSettings.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/LeadTimeForChangesControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Web/Controllers/HomeController.cs, DevOpsMetrics/DevOpsMetrics.Web/Models/ProjectViewModel.cs, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/DeploymentFrequency.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/Index.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/LeadTimeForChanges.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/MeanTimeToRestore.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/Project.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_ChangeFailureRate.cshtml, DevOpsMetrics/DevOpsMetrics.Web/wwwroot/css/site.css, README.md
=> Updated UI for website

DevOpsMetrics/DevOpsMetrics.Service/Common.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/MeanTimeToRestoreDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/TableStorage/AzureTableStorageDA.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/ChangeFailureRateBuild.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/ChangeFailureRateModel.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/MeanTimeToRestoreModel.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/TableStorageAuth.cs, DevOpsMetrics/DevOpsMetrics.Service/appsettings.json, DevOpsMetrics/DevOpsMetrics.Tests/Common.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/MeanTimeToRestoreDATests.cs, DevOpsMetrics/DevOpsMetrics.Tests/appsettings.json, README.md
=> Renamed MTTR table and added new change failure rate table

DevOpsMetrics/DevOpsMetrics.Core/ChangeFailureRate.cs, DevOpsMetrics/DevOpsMetrics.Core/DeploymentFrequency.cs, DevOpsMetrics/DevOpsMetrics.Core/LeadTimeForChanges.cs, DevOpsMetrics/DevOpsMetrics.Core/MeanTimeToRestore.cs, DevOpsMetrics/DevOpsMetrics.Service/Common.cs, DevOpsMetrics/DevOpsMetrics.Service/Controllers/ChangeFailureRateController.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/ChangeFailureRateDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/MeanTimeToRestoreDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/TableStorage/AzureTableStorageDA.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/ChangeFailureRateBuild.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/ChangeFailureRateModel.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/TableStorageAuth.cs, DevOpsMetrics/DevOpsMetrics.Service/appsettings.json, DevOpsMetrics/DevOpsMetrics.Tests/Common.cs, DevOpsMetrics/DevOpsMetrics.Tests/Core/ChangeFailureRateTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Core/MeanTimeToRestoreTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/ChangeFailureRateControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/ChangeFailureRateDATests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/MeanTimeToRestoreControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/MeanTimeToRestoreDATests.cs, DevOpsMetrics/DevOpsMetrics.Tests/appsettings.json, DevOpsMetrics/DevOpsMetrics.Web/Controllers/HomeController.cs, DevOpsMetrics/DevOpsMetrics.Web/Models/ProjectViewModel.cs, DevOpsMetrics/DevOpsMetrics.Web/Services/ServiceAPIClient.cs, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/ChangeFailureRate.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/DeploymentFrequency.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/Index.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/Project.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_ChangeFailureRate.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_Deployments.cshtml
=> Adding change failure rate base data to service and website

DevOpsMetrics/DevOpsMetrics.Service/DataAccess/ChangeFailureRateDA.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/ChangeFailureRateDATests.cs
=> Created limit for change rate failure

DevOpsMetrics/DevOpsMetrics.Service/DataAccess/LeadTimeForChangesDA.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/LeadTimeForChangesDATests.cs
=> Updated lead time to limit the number of pull requests correctly

DevOpsMetrics/DevOpsMetrics.Service/Controllers/ChangeFailureRateController.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/ChangeFailureRateDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/DeploymentFrequencyDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/LeadTimeForChangesDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/MeanTimeToRestoreDA.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/ChangeFailureRateModel.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/DeploymentFrequencyModel.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/LeadTimeForChangesModel.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/MeanTimeToRestoreModel.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/ChangeFailureRateControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/ChangeFailureRateDATests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/DeploymentFrequencyControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/DeploymentFrequencyDATests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/LeadTimeForChangesControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/LeadTimeForChangesDATests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/MeanTimeToRestoreControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/MeanTimeToRestoreDATests.cs, DevOpsMetrics/DevOpsMetrics.Web/Controllers/HomeController.cs, DevOpsMetrics/DevOpsMetrics.Web/Models/NumberOfDaysItem.cs, DevOpsMetrics/DevOpsMetrics.Web/Models/ProjectUpdateViewModel.cs, DevOpsMetrics/DevOpsMetrics.Web/Services/ServiceAPIClient.cs, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/ChangeFailureRateUpdates.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_ChangeFailureRate.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_Deployments.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_LeadTimeForChanges.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_MeanTimeToRestore.cshtml, DevOpsMetrics/DevOpsMetrics.Web/wwwroot/css/site.css, README.md
=> Ui upgrades

DevOpsMetrics/DevOpsMetrics.Function/DevOpsMetrics.Function.csproj, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/LeadTimeForChangesDA.cs, DevOpsMetrics/DevOpsMetrics.Tests/DevOpsMetrics.Tests.csproj, DevOpsMetrics/DevOpsMetrics.Tests/Service/LeadTimeForChangesDATests.cs, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/ChangeFailureRate.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/DeploymentFrequency.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/LeadTimeForChanges.cshtml, README.md
=> Updated code to rename master branches to main

.github/workflows/dotnetcore.yml, DevOpsMetrics/.editorconfig, DevOpsMetrics/DevOpsMetrics.Core/ChangeFailureRate.cs, DevOpsMetrics/DevOpsMetrics.Core/MeanTimeToRestore.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/APIAccess/AzureDevOpsAPIAccess.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/APIAccess/GitHubAPIAccess.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/BuildsDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/ChangeFailureRateDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/Common/FractionConverter.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/Common/ListUtility.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/DeploymentFrequencyDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/LeadTimeForChangesDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/MeanTimeToRestoreDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/TableStorage/AzureTableStorageDA.cs, DevOpsMetrics/DevOpsMetrics.Service/DataAccess/TableStorage/TableStorageCommonDA.cs, DevOpsMetrics/DevOpsMetrics.Service/GlobalSuppressions.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Azure/AzureAlert.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Azure/AzureStorageTableModel.cs, DevOpsMetrics/DevOpsMetrics.Service/Models/Common/PullRequestModel.cs, DevOpsMetrics/DevOpsMetrics.Service/Program.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/FractionConverterTests.cs, DevOpsMetrics/DevOpsMetrics.Web/Controllers/HomeController.cs, DevOpsMetrics/DevOpsMetrics.Web/Models/ProjectViewModel.cs, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/DeploymentFrequency.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Home/Project.cshtml, DevOpsMetrics/DevOpsMetrics.sln
=> Refactored some classes for logic and to make them easier to test

DevOpsMetrics/DevOpsMetrics.Service/Models/Common/Badges.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/ChangeFailureRateControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/DeploymentFrequencyControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/LeadTimeForChangesControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Tests/Service/MeanTimeToRestoreControllerTests.cs, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_ChangeFailureRate.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_Deployments.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_LeadTimeForChanges.cshtml, DevOpsMetrics/DevOpsMetrics.Web/Views/Shared/_MeanTimeToRestore.cshtml
=> Added badges to the widgets

ProbotMetrics/index.js, ProbotMetrics/package-lock.json, ProbotMetrics/package.json, ProbotMetrics/settings.json, ProbotMetrics/src/generateDevopsMetrics.js, ProbotMetrics/src/getGithubSettings.js, ProbotMetrics/src/postDevopsMetrics.js, ProbotMetrics/src/prepareDevOpsMetrics.js
Remove URLs, allow custom intervals
=> Settings Json

README.md, src/DevOpsMetrics.Core/SLA.cs, src/DevOpsMetrics.Core/Scaling.cs, src/DevOpsMetrics.Function/DevOpsMetrics.Function.csproj, src/DevOpsMetrics.FunctionalTests/DevOpsMetrics.FunctionalTests.csproj, src/DevOpsMetrics.Service/DataAccess/MeanTimeToRestoreDA.cs, src/DevOpsMetrics.Service/DevOpsMetrics.Service.csproj, src/DevOpsMetrics.Service/Models/Common/MeanTimeToRestoreModel.cs, src/DevOpsMetrics.Service/Models/Common/SLAModel.cs, src/DevOpsMetrics.Tests/Core/MeanTimeToRestoreTests.cs, src/DevOpsMetrics.Tests/Core/SLATests.cs, src/DevOpsMetrics.Tests/DevOpsMetrics.Tests.csproj, src/DevOpsMetrics.Tests/Service/MeanTimeToRestoreControllerTests.cs, src/ProbotMetrics/index.js
=> Adding SLA to the service - an experiment

src/DevOpsMetrics.Core/SLA.cs, src/DevOpsMetrics.Service/DataAccess/MeanTimeToRestoreDA.cs, src/DevOpsMetrics.Tests/Core/MeanTimeToRestoreTests.cs, src/DevOpsMetrics.Tests/Core/SLATests.cs, src/DevOpsMetrics.Tests/Service/MeanTimeToRestoreDATests.cs, src/DevOpsMetrics.Web/Views/Home/Index.cshtml, src/DevOpsMetrics.Web/Views/Home/MeanTimeToRestore.cshtml, src/DevOpsMetrics.Web/Views/Shared/_MeanTimeToRestore.cshtml
=> Fixed new MTTR bug I introduced and updated the SLA options

src/DevOpsMetrics.Core/DataAccess/BuildsDA.cs, src/DevOpsMetrics.Core/DataAccess/ChangeFailureRateDA.cs, src/DevOpsMetrics.Core/DataAccess/Common/FractionConverter.cs, src/DevOpsMetrics.Core/DataAccess/DeploymentFrequencyDA.cs, src/DevOpsMetrics.Core/DataAccess/LeadTimeForChangesDA.cs, src/DevOpsMetrics.Core/DataAccess/MeanTimeToRestoreDA.cs, src/DevOpsMetrics.Core/DataAccess/PullRequestDA.cs, src/DevOpsMetrics.Core/DataAccess/TableStorage/AzureTableStorageDA.cs, src/DevOpsMetrics.Core/DataAccess/TableStorage/IAzureTableStorageDA.cs, src/DevOpsMetrics.Core/DataAccess/TableStorage/PartitionKeys.cs, src/DevOpsMetrics.Core/DataAccess/TableStorage/TableStorageCommonDA.cs, src/DevOpsMetrics.Core/Models/Common/ProjectLog.cs, src/DevOpsMetrics.Core/Models/Common/TableStorageConfiguration.cs, src/DevOpsMetrics.Function/NightlyProcessor.cs, src/DevOpsMetrics.Function/ServiceApiClient.cs, src/DevOpsMetrics.Service/Common.cs, src/DevOpsMetrics.Service/Controllers/TableStorageController.cs, src/DevOpsMetrics.Service/appsettings.json, src/DevOpsMetrics.Tests/Common.cs, src/DevOpsMetrics.Tests/Service/AzureMonitorTests.cs, src/DevOpsMetrics.Tests/Service/SettingsDATests.cs, src/DevOpsMetrics.Tests/Service/TableStorageControllerDATests.cs, src/DevOpsMetrics.Tests/Service/TableStorageDATests.cs, src/DevOpsMetrics.Tests/appsettings.json
=> Added logging and refactored to Core classes

src/DevOpsMetrics.Core/DataAccess/TableStorage/AzureTableStorageDA.cs, src/DevOpsMetrics.Core/DataAccess/TableStorage/IAzureTableStorageDA.cs, src/DevOpsMetrics.Core/DataAccess/TableStorage/PartitionKeys.cs, src/DevOpsMetrics.Core/Models/AzureDevOps/AzureDevOpsSettings.cs, src/DevOpsMetrics.Core/Models/GitHub/GitHubSettings.cs, src/DevOpsMetrics.FunctionalTests/DevOpsMetrics.FunctionalTests.csproj, src/DevOpsMetrics.FunctionalTests/GlobalSuppressions.cs, src/DevOpsMetrics.FunctionalTests/ServiceSmokeTest.cs, src/DevOpsMetrics.Service/Controllers/BuildsController.cs, src/DevOpsMetrics.Service/Controllers/DeploymentFrequencyController.cs, src/DevOpsMetrics.Service/Controllers/LeadTimeForChangesController.cs, src/DevOpsMetrics.Service/Controllers/PullRequestsController.cs, src/DevOpsMetrics.Service/Controllers/SettingsController.cs, src/DevOpsMetrics.Service/DevOpsMetrics.Service.csproj, src/DevOpsMetrics.Service/Program.cs, src/DevOpsMetrics.Tests/Core/SettingsDATests.cs, src/DevOpsMetrics.Tests/Service/DeploymentFrequencyControllerTests.cs, src/DevOpsMetrics.Tests/Service/LeadTimeForChangesControllerTests.cs, src/DevOpsMetrics.Tests/Service/TableStorageControllerDATests.cs
fixes #85 (move secrets into a key vault)
- removed secrets from setting file
- Added new API to create secret in key vault
- Updated GitHub API to support this change
- Updated Azure DevOps API to support this change
=> Added key vault configuration for GitHub, Azure DevOps. and updated settings tests

.github/workflows/dotnetcore.yml
=> Fix to pipeline to resolve .NET 6 secrets change

.github/workflows/codeql-analysis.yml, .github/workflows/dotnetcore.yml, src/DevOpsMetrics.FunctionalTests/DevOpsMetrics.FunctionalTests.csproj, src/DevOpsMetrics.Tests/DevOpsMetrics.Tests.csproj
This pull request primarily updates various actions and package versions used in the project. The most significant changes include updating the version of `github/codeql-action/analyze` in the `codeql-analysis.yml` workflow, updating the versions of `actions/upload-artifact`, `actions/download-artifact` in the `dotnetcore.yml` workflow, and updating the versions of `MSTest.TestAdapter`, `MSTest.TestFramework`, and `Selenium.WebDriver` in the project files.
GitHub Workflow Updates:
* [`.github/workflows/codeql-analysis.yml`](diffhunk://#diff-63bd641104d10e25f141d518a16b22a151d125e12701df2f9e79734b23b90188L75-R75): Updated `github/codeql-action/analyze` from version 2 to version 3.
* [`.github/workflows/dotnetcore.yml`](diffhunk://#diff-ac55abaaeaf67fb06efd5a2233f5a5f9ea20e835e7c502ff05c1bf2 …
=> Packages update

.github/workflows/codeql-analysis.yml
This pull request includes updates to the CodeQL actions used in the GitHub workflow file `.github/workflows/codeql-analysis.yml`. The changes involve updating the versions of the `Initialize CodeQL` and `Autobuild` actions from version 2 to version 3.
* `Initialize CodeQL` action: Updated the version of the `Initialize CodeQL` action from `v2` to `v3`. This action initializes the CodeQL tools for scanning the codebase.
* `Autobuild` action: Updated the version of the `Autobuild` action from `v2` to `v3`. This action attempts to build any compiled languages such as C/C++, C#, or Java.
=> Updated action

.github/workflows/codeql-analysis.yml, .github/workflows/dotnetcore.yml, src/DevOpsMetrics.Cmd/DevOpsMetrics.Cmd.csproj, src/DevOpsMetrics.Function/DevOpsMetrics.Function.csproj, src/DevOpsMetrics.FunctionalTests/DevOpsMetrics.FunctionalTests.csproj, src/DevOpsMetrics.Service/DevOpsMetrics.Service.csproj, src/DevOpsMetrics.Tests/DevOpsMetrics.Tests.csproj
This pull request primarily updates package versions across multiple files. These updates include changes to the versions of `actions/setup-dotnet`, `gittools/actions/gitversion/setup`, `gittools/actions/gitversion/execute`, `Azure.Identity`, `Selenium.WebDriver`, `Selenium.WebDriver.ChromeDriver`, `Microsoft.VisualStudio.Web.CodeGeneration.Design`, and `Microsoft.AspNetCore.TestHost`.
=> Updating Packages
